### ISSUE TITLE
at startup is no selection possible

### ISSUE THREAD

**Issue by forrobosoft** [8devices/u-boot#1]
Hi!
i am a beginner
I own 2 boards carambola

the first boot I had the opportunity to meet a selection,
But after a system upgrade, the selection will not be possible

fw_printenv edition
bootcmd = bootp; setenv bootargs root = / dev / nfs nfsroot = $ {serverip}: $ {rootpath} ip = $ {ipaddr}: $ {serverip}: $ {GatewayIP}: $ {netmask}: $ {hostname}: : off; bootm
baudrate = 115200
bootdelay = 10
"
Please choose the operation:
1: Load system code to SDRAM via TFTP.
2: Load system code then write to Flash via TFTP.
3: Boot system code via Flash (default).
4: Entr boot command line interface.
7: Load Boot Loader code then write to Flash via Serial.
9: Load Boot Loader code then write to Flash via TFTP.

You choosed 3

0
"
what can I do to get a choice

**Comment by valinskas** [comment]
Hi,

what do you mean by "a system upgrade". Was it u-boot upgrade ?
Please post full serial console log starting device power on, u-boot
start up and linux kernel loading.

**Comment by forrobosoft** [comment]
Am Samstag, 29. Dezember 2012, 12:34:22 schrieb Žilvinas Valinskas:

> Hi,
> 
> what do you mean by "a system upgrade". Was it u-boot upgrade ?
> Please post full serial console log starting device power on, u-boot
> start up and linux kernel loading.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/8devices/u-boot/issues/1#issuecomment-11757380

Hi

no U-Boot upgrade,  it was a sysupgrade

ok i mean after build a new image and than i make sysupgrade for this new 
image too my carambola board

and now i have no time to make a choice 
in U-Boot menu

before 
5  4   3   2    1

and now
0

all other works fine

## this is the out put to stdin

```
U-Boot 1.1.3 (Feb 20 2012 - 16:20:22)

Board: Ralink APSoC DRAM:  32 MB
relocate_code Pointer at: 81fb0000
config usb..
flash_protect ON: from 0xBF000000 to 0xBF01E757
flash_protect ON: from 0xBF030000 to 0xBF030FFF
*** Warning - bad CRC, using default environment

============================================
Ralink UBoot Version: 3.5.0.0
--------------------------------------------
ASIC 3052_MP2 (Port5<->None)
DRAM component: 256 Mbits SDR
DRAM bus: 16 bit
Total memory: 32 MBytes
Flash component: NOR Flash
Date:Feb 20 2012  Time:16:20:22
============================================
icache: sets:256, ways:4, linesz:32 ,total:32768
dcache: sets:128, ways:4, linesz:32 ,total:16384

 ##### The CPU freq = 320 MHZ ####
 estimate memory size =32 Mbytes

Please choose the operation:
   1: Load system code to SDRAM via TFTP.
   2: Load system code then write to Flash via TFTP.
   3: Boot system code via Flash (default).
   4: Entr boot command line interface.
   7: Load Boot Loader code then write to Flash via Serial.
   9: Load Boot Loader code then write to Flash via TFTP.
 0

3: System Boot system code via Flash.
## Booting image at bf050000 ...
   Image Name:   MIPS OpenWrt Linux-3.3.8
   Created:      2012-12-23   8:33:11 UTC
   Image Type:   MIPS Linux Kernel Image (lzma compressed)
   Data Size:    860238 Bytes = 840.1 kB
   Load Address: 80000000
   Entry Point:  80000000
   Verifying Checksum ... OK
   Uncompressing Kernel Image ... OK
No initrd
## Transferring control to Linux (at address 80000000) ...
## Giving linux memsize in MB, 32

Starting kernel ...
```

---

this is the output from fw_printenv

fw_printenv edition
bootcmd = bootp; setenv bootargs root = / dev / nfs nfsroot = $ {serverip}: $ 
{rootpath} ip = $ {ipaddr}: $ {serverip}: $ {GatewayIP}: $ {netmask}: $ 
{hostname}: : off; bootm
baudrate = 115200
bootdelay = 10

---

good luck for the next year

thanks for your reply

tino

**Comment by valinskas** [comment]
Hmm. if that was a sysupgrade ... it means no u-boot upgrade. :\
I just don't understand how it could be related with u-boot ...  Then
again:

```
U-Boot 1.1.3 (Feb 20 2012 - 16:20:22)

Board: Ralink APSoC DRAM:  32 MB
relocate_code Pointer at: 81fb0000
config usb..
flash_protect ON: from 0xBF000000 to 0xBF01E757
flash_protect ON: from 0xBF030000 to 0xBF030FFF
*** Warning - bad CRC, using default environment

```

This tells me that u-boot is ignoring configuration on flash.
U-boot is using compiled in default settings. If I remember
correctly "bootdelay" is set 1 by default.

Can you power cycle board and then press '4' several
times. Don't wait to u-boot banner to appear. You should
see prompt like this:

```
rt3052# 
```

Then you can change bootdelay by:

```
rt3052# setevn bootdelay=5
rt3052# saveenv
rt3052# reset
```

**Comment by forrobosoft** [comment]
Am Montag, 31. Dezember 2012, 05:44:47 schrieb Žilvinas Valinskas:

> Hmm. if that was a sysupgrade ... it means no u-boot upgrade. :\
> I just don't understand how it could be related with u-boot ...  Then
> again:
> 
> ```
> U-Boot 1.1.3 (Feb 20 2012 - 16:20:22)
> 
> Board: Ralink APSoC DRAM:  32 MB
> relocate_code Pointer at: 81fb0000
> config usb..
> flash_protect ON: from 0xBF000000 to 0xBF01E757
> flash_protect ON: from 0xBF030000 to 0xBF030FFF
> *** Warning - bad CRC, using default environment
> 
> ```
> 
> This tells me that u-boot is ignoring configuration on flash.
> U-boot is using compiled in default settings. If I remember
> correctly "bootdelay" is set 1 by default.
> 
> Can you power cycle board and then press '4' several
> times. Don't wait to u-boot banner to appear. You should
> see prompt like this:
> 
> ```
> rt3052#
> ```
> 
> Then you can change bootdelay by:
> 
> ```
> rt3052# setevn bootdelay=5
> rt3052# saveenv
> rt3052# reset
> ```
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/8devices/u-boot/issues/1#issuecomment-11777522

Hi 

thats was it
now i have more time too choose on u-boot

many thanks

tino

**Comment by valinskas** [comment]
I am glad I could help with. Good luck in the next year!
