### ISSUE TITLE
Carambola 2 bootargs variable is disregarded

### ISSUE THREAD

**Issue by hutorny** [8devices/u-boot#3]
<h4>Synopsis</h4>

In the boot menu type
<code>
setenv bootargs console=ttyS0,115200n8 noinitrd rw ip=192.168.28.20:192.168.28.27:192.168.28.1:255.255.255.0:ca::off: root=/dev/nfs nfsroot=192.168.28.27:/tftpboot/root,nolock
boot
</code>

Carambola boots as usual

<h4>Expected behaviour</h4>

root NFS mount as bootargs prescribes

<h4>Version</h4>

U-Boot 1.1.4 (Feb  8 2013 - 11:41:32)

**Comment by valinskas** [comment]
It's OpenWRT feature. Linux kernel is compiled so it does ignore all parameters from boot looder.
It is done mostly to work around broken boot loaders, especially those that have hard coded booting
parameters and thus impossible to override (unless ignored of course as done by WRT),

**Comment by valinskas** [comment]
```
CONFIG_CMDLINE="console=ttyS0,9600 rootfstype=squashfs,jffs2"
```

You can use it to provide NFS root parameters. It means you need to recompile kernel.

**Comment by drasko** [comment]
This is not quite correct. U-Boot bootargs should ALWAYS override kernel CMDLINE, unless CMDLINE_OVERRIDE is configured.

However, Carambola 2 kernel has an issue that it does not take U-Boot bootargs even when CMDLINE_OVERRIDE is not set, which is wrong and makes development harder.

Some similar issues: 
http://forums.xilinx.com/t5/Embedded-Linux/U-Boot-not-passing-bootargs-to-Linux/td-p/343883
https://forum.openwrt.org/viewtopic.php?id=47078&p=2

**Comment by valinskas** [comment]
Usually OpenWrt kernels tend to ignore boot-loader parameters. Parameters are ignored mostly
because some boot loaders have compiled in parameters and impossible to change them at all
without recompiling boot loader (and no sources are available).

Care to send a patch ?

**Comment by valinskas** [comment]
Let me  try to debug what is going on there.

**Comment by mantas-p** [comment]
OpenWRT ignores bootargs supplied by u-boot because of kernel config option:

```
CONFIG_IMAGE_CMDLINE_HACK=y
```

introduced in linux-3.7.9/patches/platform/508-MIPS-ath79-prom-image-command-line-hack.patch

After disabling this option, openwrt accepts bootargs form u-boot, but default bootargs need to be supplied for image to boot sucessfuly:

```
setenv bootargs board=CARAMBOLA2 console=ttyATH0,115200 mtdparts=spi0.0:256k(u-boot)ro,64k(u-boot-env)ro,2048k(kernel),13888k(rootfs),64k(nvram),64k(art)ro,15936k@0x50000(firmware)
```

**Comment by drasko** [comment]
Disabling CONFIG_IMAGE_CMDLINE_HACK provokes "Command line marker not found!" compilation error in my case...

Actually, there seems to be a bug in the patch-cmdline tool: 
/home/drasko/carambola2/staging_dir/host/bin/patch-cmdline /home/drasko/carambola2/build_dir/target-mips_r2_uClibc-0.9.33.2/linux-ar71xx_generic/tmp/vmlinux-carambola2 "board=CARAMBOLA2 console=ttyATH0,115200 mtdparts=spi0.0:256k(u-boot)ro,64k(u-boot-env)ro,2048k(kernel),13888k(rootfs),64k(nvram),64k(art)ro,15936k@0x50000(firmware)"
Command line marker not found!

Can it bee that I am missing some configuration? @mantas-p did you just disable CONFIG_IMAGE_CMDLINE_HACK, or you disabled built-in kernel command line (CONFIG_CMDLINE_BOOL) also?

**Comment by mantas-p** [comment]
When CONFIG_IMAGE_CMDLINE_HACK is disabled, patch-cmdline should not be run, patch below:

```
--- target/linux/ar71xx/image/Makefile.orig     2013-11-11 09:33:15.145554877 +0200
+++ target/linux/ar71xx/image/Makefile  2013-11-11 09:33:22.665554689 +0200
@@ -74,13 +74,13 @@

 define PatchKernelLzma
        cp $(KDIR)/vmlinux $(KDIR_TMP)/vmlinux-$(1)
-       $(STAGING_DIR_HOST)/bin/patch-cmdline $(KDIR_TMP)/vmlinux-$(1) "$(strip $(2))"
+#      $(STAGING_DIR_HOST)/bin/patch-cmdline $(KDIR_TMP)/vmlinux-$(1) "$(strip $(2))"
        $(call CompressLzma,$(KDIR_TMP)/vmlinux-$(1),$(KDIR_TMP)/vmlinux-$(1).bin.lzma,$(3))
 endef

 define PatchKernelGzip
        cp $(KDIR)/vmlinux $(KDIR_TMP)/vmlinux-$(1)
-       $(STAGING_DIR_HOST)/bin/patch-cmdline $(KDIR_TMP)/vmlinux-$(1) "$(strip $(2))"
+#      $(STAGING_DIR_HOST)/bin/patch-cmdline $(KDIR_TMP)/vmlinux-$(1) "$(strip $(2))"
        gzip -9 -c $(KDIR_TMP)/vmlinux-$(1) > $(KDIR_TMP)/vmlinux-$(1).bin.gz
 endef
```

CONFIG_CMDLINE_BOOL was enabled
